"""Shared dry-run payload coverage cases for API schema gates."""

DRY_RUN_PAYLOAD_EXCLUSIONS = {
    "adextensions.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "adgroups.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "adimages.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "advideos.get": "Read-path required SelectionCriteria is covered by WSDL selection criteria tests.",
    "audiencetargets.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "bidmodifiers.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "bids.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "businesses.get": "Read path omits optional SelectionCriteria when --ids is absent.",
    "campaigns.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "creatives.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "dynamicads.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "dynamicfeedadtargets.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "feeds.get": "Read path omits optional SelectionCriteria when --ids is absent.",
    "keywordbids.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "keywords.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "leads.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "negativekeywordsharedsets.get": "Read path omits optional SelectionCriteria when --ids is absent.",
    "sitelinks.get": "Read path omits optional SelectionCriteria when --ids is absent.",
    "smartadtargets.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "turbopages.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "vcards.get": "Read path omits optional SelectionCriteria when --ids is absent.",
    "adextensions.add": "Callout-only add; covered by command-level dry-run tests.",
    "adgroups.add": "Requires group-type-specific typed payload fixtures; tracked separately from schema smoke coverage.",
    "adgroups.update": "Requires typed update payload fixtures; tracked separately from schema smoke coverage.",
    "adimages.add": "Requires image-data or image-file fixtures that are better covered by command tests.",
    "ads.add": "Requires TEXT_AD and TEXT_IMAGE_AD payload variants; covered by focused dry-run tests.",
    "ads.archive": "Lifecycle alias of the same request shape family as campaigns/keywords lifecycle commands.",
    "ads.get": "Read path with rich field-selection options; payload contract differs from mutating coverage focus.",
    "ads.resume": "Lifecycle alias in the same request-shape family as covered resume/delete actions.",
    "ads.suspend": "Lifecycle alias in the same request-shape family as covered resume/delete actions.",
    "ads.unarchive": "Lifecycle alias in the same request-shape family as covered resume/delete actions.",
    "ads.update": "Requires large heterogeneous ad payload variants; covered by focused dry-run tests.",
    "advideos.add": "Requires media payload fixture not worth duplicating in generic schema smoke coverage.",
    "audiencetargets.resume": "Same simple Ids payload family as covered delete/set-bids actions.",
    "audiencetargets.suspend": "Same simple Ids payload family as covered delete/set-bids actions.",
    "bidmodifiers.add": "Requires modifier-type-specific typed flag fixtures.",
    "bidmodifiers.delete": "Helper/legacy surface; not part of strict WSDL parity claim.",
    "bidmodifiers.set": "Requires modifier-type-specific typed flag fixtures.",
    "campaigns.add": "Requires campaign-type-specific typed payload variants; covered by focused dry-run tests.",
    "campaigns.suspend": "Same lifecycle payload family as covered campaigns.delete/archive/resume.",
    "campaigns.unarchive": "Same lifecycle payload family as covered campaigns.delete/archive/resume.",
    "campaigns.update": "Requires typed budget/date/status variants; covered by focused dry-run tests.",
    "agencyclients.add": "Runtime-deprecated method (Yandex error 3500); CLI rejects with UsageError before reaching dry-run. See RUNTIME_DEPRECATED_METHODS.",
    "dynamicads.add": "Requires condition-spec payload fixtures with optional bid fields.",
    "dynamicads.resume": "Same simple Ids payload family as covered delete/set-bids actions.",
    "dynamicads.suspend": "Same simple Ids payload family as covered delete/set-bids actions.",
    "dynamicfeedadtargets.add": "Covered by test_dry_run.py::test_dynamicfeedadtargets_add_payload.",
    "dynamicfeedadtargets.delete": "Covered by test_dry_run.py::test_dynamicfeedadtargets_delete_payload.",
    "dynamicfeedadtargets.resume": "Covered by test_dry_run.py::test_dynamicfeedadtargets_resume_payload.",
    "dynamicfeedadtargets.set-bids": "Covered by test_dry_run.py::test_dynamicfeedadtargets_set_bids_payload.",
    "dynamicfeedadtargets.suspend": "Covered by test_dry_run.py::test_dynamicfeedadtargets_suspend_payload.",
    "strategies.add": "Covered by test_dry_run.py::test_strategies_add_payload.",
    "strategies.archive": "Covered by test_dry_run.py::test_strategies_archive_payload.",
    "strategies.unarchive": "Covered by test_dry_run.py::test_strategies_unarchive_payload.",
    "strategies.update": "Covered by test_dry_run.py::test_strategies_update_payload.",
    "feeds.add": "Current WSDL schema parser treats feed source variants like required siblings; keep covered by command-level dry-run tests.",
    "keywords.add": "Requires keyword/addition payload variants; covered by focused dry-run tests.",
    "keywords.resume": "Same simple Ids payload family as covered keywords.delete/suspend.",
    "keywords.update": "Requires keyword update payload variants; covered by focused dry-run tests.",
    "retargeting.add": "Requires typed --rule payload fixtures.",
    "smartadtargets.resume": "Same simple Ids payload family as covered delete/set-bids actions.",
    "smartadtargets.suspend": "Same simple Ids payload family as covered delete/set-bids actions.",
    "vcards.add": "Requires large contact-card payload fixture not needed for generic schema smoke coverage.",
    "reports.get": "Reports API uses a custom TSV endpoint; payload contract is covered by test_reports_request_builder_contract.",
    "v4account.account-management": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4account.enable-shared-account": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4events.get-events-log": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4finance.check-payment": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4finance.create-invoice": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4finance.get-clients-units": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4finance.get-credit-limits": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4finance.pay-campaigns": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4finance.transfer-money": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4goals.get-retargeting-goals": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4goals.get-stat-goals": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4tags.get-banners": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4tags.get-campaigns": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4tags.update-banners": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4tags.update-campaigns": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4wordstat.create-report": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4wordstat.delete-report": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4wordstat.get-report": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4wordstat.list-reports": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
}

PAYLOAD_CASES = [
    (
        "agencyclients",
        "update",
        [
            "agencyclients",
            "update",
            "--client-id",
            "42",
            "--client-info",
            "Agency client",
            "--phone",
            "+70000000000",
            "--notification-email",
            "ops@example.com",
            "--notification-lang",
            "EN",
            "--email-subscription",
            "RECEIVE_RECOMMENDATIONS=YES",
            "--setting",
            "DISPLAY_STORE_RATING=NO",
            "--grant",
            "EDIT_CAMPAIGNS=YES",
        ],
    ),
    (
        "agencyclients",
        "addPassportOrganization",
        [
            "agencyclients",
            "add-passport-organization",
            "--name",
            "Org",
            "--currency",
            "RUB",
            "--notification-email",
            "ops@example.com",
            "--notification-lang",
            "EN",
            "--no-send-account-news",
            "--send-warnings",
        ],
    ),
    (
        "agencyclients",
        "addPassportOrganizationMember",
        [
            "agencyclients",
            "add-passport-organization-member",
            "--passport-organization-login",
            "org-login",
            "--role",
            "CHIEF",
            "--invite-email",
            "user@example.com",
        ],
    ),
    (
        "audiencetargets",
        "add",
        [
            "audiencetargets",
            "add",
            "--adgroup-id",
            "100",
            "--retargeting-list-id",
            "200",
            "--bid",
            "12000000",
            "--priority",
            "HIGH",
        ],
    ),
    (
        "audiencetargets",
        "setBids",
        [
            "audiencetargets",
            "set-bids",
            "--id",
            "10",
            "--context-bid",
            "5000000",
            "--priority",
            "LOW",
        ],
    ),
    (
        "bids",
        "set",
        [
            "bids",
            "set",
            "--keyword-id",
            "123",
            "--bid",
            "1500000",
        ],
    ),
    (
        "bids",
        "setAuto",
        [
            "bids",
            "set-auto",
            "--keyword-id",
            "123",
            "--max-bid",
            "20000000",
            "--position",
            "PREMIUMBLOCK",
            "--scope",
            "SEARCH",
        ],
    ),
    (
        "clients",
        "update",
        [
            "clients",
            "update",
            "--client-info",
            "Client note",
            "--phone",
            "+70000000000",
            "--notification-email",
            "client@example.com",
            "--notification-lang",
            "EN",
            "--email-subscription",
            "TRACK_POSITION_CHANGES=NO",
            "--setting",
            "CORRECT_TYPOS_AUTOMATICALLY=YES",
            "--tin-type",
            "LEGAL",
            "--tin",
            "1234567890",
        ],
    ),
    (
        "creatives",
        "add",
        [
            "creatives",
            "add",
            "--video-id",
            "video-id",
        ],
    ),
    (
        "feeds",
        "update",
        [
            "feeds",
            "update",
            "--id",
            "18",
            "--name",
            "Renamed feed",
        ],
    ),
    (
        "dynamictextadtargets",
        "setBids",
        [
            "dynamicads",
            "set-bids",
            "--id",
            "10",
            "--bid",
            "3000000",
            "--context-bid",
            "2000000",
            "--priority",
            "HIGH",
        ],
    ),
    (
        "keywordbids",
        "set",
        [
            "keywordbids",
            "set",
            "--keyword-id",
            "321",
            "--search-bid",
            "1100000",
            "--network-bid",
            "900000",
        ],
    ),
    (
        "keywordbids",
        "setAuto",
        [
            "keywordbids",
            "set-auto",
            "--keyword-id",
            "321",
            "--target-traffic-volume",
            "100",
            "--increase-percent",
            "10",
            "--bid-ceiling",
            "12500000",
        ],
    ),
    (
        "negativekeywordsharedsets",
        "add",
        [
            "negativekeywordsharedsets",
            "add",
            "--name",
            "Shared negatives",
            "--keywords",
            "cheap,free",
        ],
    ),
    (
        "negativekeywordsharedsets",
        "update",
        [
            "negativekeywordsharedsets",
            "update",
            "--id",
            "19",
            "--keywords",
            "cheap,free",
        ],
    ),
    (
        "retargetinglists",
        "update",
        [
            "retargeting",
            "update",
            "--id",
            "55",
            "--name",
            "Renamed",
            "--rule",
            "ANY:12345:30",
        ],
    ),
    (
        "sitelinks",
        "add",
        [
            "sitelinks",
            "add",
            "--sitelink",
            "Docs|https://example.com/docs|Desk",
        ],
    ),
    (
        "smartadtargets",
        "add",
        [
            "smartadtargets",
            "add",
            "--adgroup-id",
            "77",
            "--name",
            "Audience A",
            "--audience",
            "ALL_SEGMENTS",
            "--condition",
            "CATEGORY_ID:EQUALS:42",
            "--average-cpc",
            "3000000",
            "--priority",
            "HIGH",
        ],
    ),
    (
        "smartadtargets",
        "update",
        [
            "smartadtargets",
            "update",
            "--id",
            "66",
            "--name",
            "Audience B",
            "--average-cpc",
            "1000000",
            "--priority",
            "LOW",
        ],
    ),
    (
        "smartadtargets",
        "setBids",
        [
            "smartadtargets",
            "set-bids",
            "--id",
            "11",
            "--average-cpc",
            "1500000",
            "--average-cpa",
            "2500000",
            "--priority",
            "LOW",
        ],
    ),
    (
        "campaigns",
        "delete",
        ["campaigns", "delete", "--id", "12"],
    ),
    (
        "campaigns",
        "archive",
        ["campaigns", "archive", "--id", "12"],
    ),
    (
        "campaigns",
        "resume",
        ["campaigns", "resume", "--id", "12"],
    ),
    (
        "ads",
        "delete",
        ["ads", "delete", "--id", "7"],
    ),
    (
        "ads",
        "moderate",
        ["ads", "moderate", "--id", "7"],
    ),
    (
        "keywords",
        "delete",
        ["keywords", "delete", "--id", "8"],
    ),
    (
        "keywords",
        "suspend",
        ["keywords", "suspend", "--id", "8"],
    ),
    (
        "adgroups",
        "delete",
        ["adgroups", "delete", "--id", "14"],
    ),
    (
        "adextensions",
        "delete",
        ["adextensions", "delete", "--id", "15"],
    ),
    (
        "adimages",
        "delete",
        ["adimages", "delete", "--hash", "image-hash"],
    ),
    (
        "audiencetargets",
        "delete",
        ["audiencetargets", "delete", "--id", "16"],
    ),
    (
        "dynamictextadtargets",
        "delete",
        ["dynamicads", "delete", "--id", "17"],
    ),
    (
        "feeds",
        "delete",
        ["feeds", "delete", "--id", "18"],
    ),
    (
        "negativekeywordsharedsets",
        "delete",
        ["negativekeywordsharedsets", "delete", "--id", "19"],
    ),
    (
        "retargetinglists",
        "delete",
        ["retargeting", "delete", "--id", "20"],
    ),
    (
        "sitelinks",
        "delete",
        ["sitelinks", "delete", "--id", "21"],
    ),
    (
        "smartadtargets",
        "delete",
        ["smartadtargets", "delete", "--id", "22"],
    ),
    (
        "vcards",
        "delete",
        ["vcards", "delete", "--id", "23"],
    ),
]

PAYLOAD_COVERED_COMMANDS = {f"{argv[0]}.{argv[1]}" for _, _, argv in PAYLOAD_CASES}
