"""Shared dry-run payload coverage cases for API schema gates."""

DRY_RUN_PAYLOAD_EXCLUSIONS = {
    "adextensions.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "adgroups.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "adimages.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "advideos.get": "Read-path required SelectionCriteria is covered by WSDL selection criteria tests.",
    "audiencetargets.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "bidmodifiers.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "bids.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "businesses.get": "Read path omits optional SelectionCriteria when --ids is absent.",
    "campaigns.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "creatives.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "dynamicads.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "dynamicfeedadtargets.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "feeds.get": "Read path omits optional SelectionCriteria when --ids is absent.",
    "keywordbids.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "keywords.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "leads.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "negativekeywordsharedsets.get": "Read path omits optional SelectionCriteria when --ids is absent.",
    "sitelinks.get": "Read path omits optional SelectionCriteria when --ids is absent.",
    "smartadtargets.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "turbopages.get": "Read-path SelectionCriteria dry-run is covered by WSDL selection criteria tests.",
    "vcards.get": "Read path omits optional SelectionCriteria when --ids is absent.",
    "ads.get": "Read path with rich field-selection options; payload contract differs from mutating coverage focus.",
    "agencyclients.add": "Runtime-deprecated method (Yandex error 3500); CLI rejects with UsageError before reaching dry-run. See RUNTIME_DEPRECATED_METHODS.",
    "dynamicfeedadtargets.add": "Covered by test_dry_run.py::test_dynamicfeedadtargets_add_payload.",
    "dynamicfeedadtargets.delete": "Covered by test_dry_run.py::test_dynamicfeedadtargets_delete_payload.",
    "dynamicfeedadtargets.resume": "Covered by test_dry_run.py::test_dynamicfeedadtargets_resume_payload.",
    "dynamicfeedadtargets.set-bids": "Covered by test_dry_run.py::test_dynamicfeedadtargets_set_bids_payload.",
    "dynamicfeedadtargets.suspend": "Covered by test_dry_run.py::test_dynamicfeedadtargets_suspend_payload.",
    "strategies.add": "Covered by test_dry_run.py::test_strategies_add_payload.",
    "strategies.archive": "Covered by test_dry_run.py::test_strategies_archive_payload.",
    "strategies.unarchive": "Covered by test_dry_run.py::test_strategies_unarchive_payload.",
    "strategies.update": "Covered by test_dry_run.py::test_strategies_update_payload.",
    "reports.get": "Reports API uses a custom TSV endpoint; payload contract is covered by test_reports_request_builder_contract.",
    "v4account.account-management": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4account.enable-shared-account": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4events.get-events-log": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4forecast.create": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4forecast.delete": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4forecast.get": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4forecast.list": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4finance.check-payment": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4finance.create-invoice": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4finance.get-clients-units": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4finance.get-credit-limits": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4finance.pay-campaigns": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4finance.transfer-money": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4goals.get-retargeting-goals": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4goals.get-stat-goals": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4tags.get-banners": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4tags.get-campaigns": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4tags.update-banners": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4tags.update-campaigns": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4wordstat.create-report": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4wordstat.delete-report": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4wordstat.get-report": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
    "v4wordstat.list-reports": "V4 Live method is not covered by V5 WSDL schemas; covered by focused dry-run tests.",
}

PAYLOAD_CASES = [
    (
        "agencyclients",
        "update",
        [
            "agencyclients",
            "update",
            "--client-id",
            "42",
            "--client-info",
            "Agency client",
            "--phone",
            "+70000000000",
            "--notification-email",
            "ops@example.com",
            "--notification-lang",
            "EN",
            "--email-subscription",
            "RECEIVE_RECOMMENDATIONS=YES",
            "--setting",
            "DISPLAY_STORE_RATING=NO",
            "--grant",
            "EDIT_CAMPAIGNS=YES",
        ],
    ),
    (
        "agencyclients",
        "addPassportOrganization",
        [
            "agencyclients",
            "add-passport-organization",
            "--name",
            "Org",
            "--currency",
            "RUB",
            "--notification-email",
            "ops@example.com",
            "--notification-lang",
            "EN",
            "--no-send-account-news",
            "--send-warnings",
        ],
    ),
    (
        "agencyclients",
        "addPassportOrganizationMember",
        [
            "agencyclients",
            "add-passport-organization-member",
            "--passport-organization-login",
            "org-login",
            "--role",
            "CHIEF",
            "--invite-email",
            "user@example.com",
        ],
    ),
    (
        "audiencetargets",
        "add",
        [
            "audiencetargets",
            "add",
            "--adgroup-id",
            "100",
            "--retargeting-list-id",
            "200",
            "--bid",
            "12000000",
            "--priority",
            "HIGH",
        ],
    ),
    (
        "audiencetargets",
        "setBids",
        [
            "audiencetargets",
            "set-bids",
            "--id",
            "10",
            "--context-bid",
            "5000000",
            "--priority",
            "LOW",
        ],
    ),
    (
        "bidmodifiers",
        "add",
        [
            "bidmodifiers",
            "add",
            "--campaign-id",
            "12",
            "--type",
            "MOBILE_ADJUSTMENT",
            "--value",
            "120",
        ],
    ),
    (
        "bidmodifiers",
        "set",
        [
            "bidmodifiers",
            "set",
            "--id",
            "10",
            "--value",
            "150",
        ],
    ),
    (
        "bids",
        "set",
        [
            "bids",
            "set",
            "--keyword-id",
            "123",
            "--bid",
            "1500000",
        ],
    ),
    (
        "bids",
        "setAuto",
        [
            "bids",
            "set-auto",
            "--keyword-id",
            "123",
            "--max-bid",
            "20000000",
            "--position",
            "PREMIUMBLOCK",
            "--scope",
            "SEARCH",
        ],
    ),
    (
        "clients",
        "update",
        [
            "clients",
            "update",
            "--client-info",
            "Client note",
            "--phone",
            "+70000000000",
            "--notification-email",
            "client@example.com",
            "--notification-lang",
            "EN",
            "--email-subscription",
            "TRACK_POSITION_CHANGES=NO",
            "--setting",
            "CORRECT_TYPOS_AUTOMATICALLY=YES",
            "--tin-type",
            "LEGAL",
            "--tin",
            "1234567890",
        ],
    ),
    (
        "creatives",
        "add",
        [
            "creatives",
            "add",
            "--video-id",
            "video-id",
        ],
    ),
    (
        "feeds",
        "update",
        [
            "feeds",
            "update",
            "--id",
            "18",
            "--name",
            "Renamed feed",
        ],
    ),
    (
        "feeds",
        "add",
        [
            "feeds",
            "add",
            "--name",
            "Test feed",
            "--url",
            "https://example.com/feed.xml",
            "--business-type",
            "RETAIL",
        ],
    ),
    (
        "dynamictextadtargets",
        "add",
        [
            "dynamicads",
            "add",
            "--adgroup-id",
            "100",
            "--name",
            "Dyn Target",
            "--condition",
            "URL:CONTAINS_ANY:catalog",
            "--bid",
            "3000000",
            "--context-bid",
            "2000000",
            "--priority",
            "HIGH",
        ],
    ),
    (
        "dynamictextadtargets",
        "setBids",
        [
            "dynamicads",
            "set-bids",
            "--id",
            "10",
            "--bid",
            "3000000",
            "--context-bid",
            "2000000",
            "--priority",
            "HIGH",
        ],
    ),
    (
        "keywordbids",
        "set",
        [
            "keywordbids",
            "set",
            "--keyword-id",
            "321",
            "--search-bid",
            "1100000",
            "--network-bid",
            "900000",
        ],
    ),
    (
        "keywordbids",
        "setAuto",
        [
            "keywordbids",
            "set-auto",
            "--keyword-id",
            "321",
            "--target-traffic-volume",
            "100",
            "--increase-percent",
            "10",
            "--bid-ceiling",
            "12500000",
        ],
    ),
    (
        "negativekeywordsharedsets",
        "add",
        [
            "negativekeywordsharedsets",
            "add",
            "--name",
            "Shared negatives",
            "--keywords",
            "cheap,free",
        ],
    ),
    (
        "negativekeywordsharedsets",
        "update",
        [
            "negativekeywordsharedsets",
            "update",
            "--id",
            "19",
            "--keywords",
            "cheap,free",
        ],
    ),
    (
        "retargetinglists",
        "update",
        [
            "retargeting",
            "update",
            "--id",
            "55",
            "--name",
            "Renamed",
            "--rule",
            "ANY:12345:30",
        ],
    ),
    (
        "sitelinks",
        "add",
        [
            "sitelinks",
            "add",
            "--sitelink",
            "Docs|https://example.com/docs|Desk",
        ],
    ),
    (
        "sitelinks",
        "add",
        [
            "sitelinks",
            "add",
            "--sitelink",
            "Главная|https://example.com/?utm=cid\\|{campaign_id}\\|gid|Подробнее",
        ],
    ),
    (
        "sitelinks",
        "add",
        [
            "sitelinks",
            "add",
            "--sitelink-json",
            (
                '[{"Title":"Главная","Href":"https://example.com/?utm=cid|{cid}",'
                '"Description":"Подробнее"}]'
            ),
        ],
    ),
    (
        "smartadtargets",
        "add",
        [
            "smartadtargets",
            "add",
            "--adgroup-id",
            "77",
            "--name",
            "Audience A",
            "--audience",
            "ALL_SEGMENTS",
            "--condition",
            "CATEGORY_ID:EQUALS:42",
            "--average-cpc",
            "3000000",
            "--priority",
            "HIGH",
        ],
    ),
    (
        "smartadtargets",
        "update",
        [
            "smartadtargets",
            "update",
            "--id",
            "66",
            "--name",
            "Audience B",
            "--average-cpc",
            "1000000",
            "--priority",
            "LOW",
        ],
    ),
    (
        "smartadtargets",
        "setBids",
        [
            "smartadtargets",
            "set-bids",
            "--id",
            "11",
            "--average-cpc",
            "1500000",
            "--average-cpa",
            "2500000",
            "--priority",
            "LOW",
        ],
    ),
    (
        "campaigns",
        "delete",
        ["campaigns", "delete", "--id", "12"],
    ),
    (
        "campaigns",
        "archive",
        ["campaigns", "archive", "--id", "12"],
    ),
    (
        "campaigns",
        "resume",
        ["campaigns", "resume", "--id", "12"],
    ),
    (
        "ads",
        "delete",
        ["ads", "delete", "--id", "7"],
    ),
    (
        "ads",
        "moderate",
        ["ads", "moderate", "--id", "7"],
    ),
    (
        "keywords",
        "delete",
        ["keywords", "delete", "--id", "8"],
    ),
    (
        "keywords",
        "suspend",
        ["keywords", "suspend", "--id", "8"],
    ),
    (
        "adgroups",
        "delete",
        ["adgroups", "delete", "--id", "14"],
    ),
    (
        "adextensions",
        "delete",
        ["adextensions", "delete", "--id", "15"],
    ),
    (
        "adimages",
        "delete",
        ["adimages", "delete", "--hash", "image-hash"],
    ),
    (
        "audiencetargets",
        "delete",
        ["audiencetargets", "delete", "--id", "16"],
    ),
    (
        "bidmodifiers",
        "delete",
        ["bidmodifiers", "delete", "--id", "10"],
    ),
    (
        "dynamictextadtargets",
        "delete",
        ["dynamicads", "delete", "--id", "17"],
    ),
    (
        "feeds",
        "delete",
        ["feeds", "delete", "--id", "18"],
    ),
    (
        "negativekeywordsharedsets",
        "delete",
        ["negativekeywordsharedsets", "delete", "--id", "19"],
    ),
    (
        "retargetinglists",
        "delete",
        ["retargeting", "delete", "--id", "20"],
    ),
    (
        "sitelinks",
        "delete",
        ["sitelinks", "delete", "--id", "21"],
    ),
    (
        "smartadtargets",
        "delete",
        ["smartadtargets", "delete", "--id", "22"],
    ),
    (
        "vcards",
        "delete",
        ["vcards", "delete", "--id", "23"],
    ),
    # --- issue #118: mutating typed-payload fixtures ---
    (
        "campaigns",
        "add",
        [
            "campaigns",
            "add",
            "--name",
            "Test Text Campaign",
            "--start-date",
            "2026-06-01",
            "--type",
            "TEXT_CAMPAIGN",
            "--budget",
            "30000000",
            "--search-strategy",
            "HIGHEST_POSITION",
            "--network-strategy",
            "SERVING_OFF",
        ],
    ),
    (
        "campaigns",
        "add",
        [
            "campaigns",
            "add",
            "--name",
            "Test RSYa Campaign",
            "--start-date",
            "2026-06-01",
            "--type",
            "TEXT_CAMPAIGN",
            "--budget",
            "50000000",
            "--search-strategy",
            "SERVING_OFF",
            "--network-strategy",
            "WB_MAXIMUM_CLICKS",
            "--text-network-weekly-spend-limit",
            "300",
            "--setting",
            "ADD_METRICA_TAG=YES",
        ],
    ),
    # --- issue #204: CPA strategy typed flags ---
    (
        "campaigns",
        "add",
        [
            "campaigns",
            "add",
            "--name",
            "Test CPA Campaign",
            "--start-date",
            "2026-06-01",
            "--type",
            "TEXT_CAMPAIGN",
            "--budget",
            "30000000",
            "--search-strategy",
            "AVERAGE_CPA",
            "--network-strategy",
            "SERVING_OFF",
            "--goal-id",
            "1234567",
            "--average-cpa",
            "500000000",
            "--bid-ceiling",
            "1000000000",
            "--counter-ids",
            "111,222",
        ],
    ),
    (
        "campaigns",
        "add",
        [
            "campaigns",
            "add",
            "--name",
            "Test Multi-Goal CPA",
            "--start-date",
            "2026-06-01",
            "--type",
            "TEXT_CAMPAIGN",
            "--search-strategy",
            "AVERAGE_CPA_MULTIPLE_GOALS",
            "--network-strategy",
            "SERVING_OFF",
            "--priority-goals",
            "1234567:80,9876543:20",
            "--bid-ceiling",
            "1000000000",
        ],
    ),
    # --- issue #364: TextCampaign.BiddingStrategy.Network typed flags ---
    (
        "campaigns",
        "add",
        [
            "campaigns",
            "add",
            "--name",
            "Test Text Network AverageCpa",
            "--start-date",
            "2026-06-01",
            "--type",
            "TEXT_CAMPAIGN",
            "--search-strategy",
            "SERVING_OFF",
            "--network-strategy",
            "AVERAGE_CPA",
            "--average-cpa",
            "100000000",
            "--goal-id",
            "1234567",
            "--text-network-weekly-spend-limit",
            "500",
            "--bid-ceiling",
            "20000000",
        ],
    ),
    (
        "campaigns",
        "update",
        [
            "campaigns",
            "update",
            "--id",
            "9999",
            "--type",
            "TEXT_CAMPAIGN",
            "--network-strategy",
            "WEEKLY_CLICK_PACKAGE",
            "--text-network-clicks-per-week",
            "150",
            "--text-network-average-cpc",
            "5",
        ],
    ),
    # --- issue #367: SmartCampaign.BiddingStrategy.Search typed flags ---
    (
        "campaigns",
        "add",
        [
            "campaigns",
            "add",
            "--name",
            "Test Smart Search AverageCpaPerCampaign",
            "--start-date",
            "2026-06-01",
            "--type",
            "SMART_CAMPAIGN",
            "--counter-id",
            "123",
            "--filter-average-cpc",
            "1000000",
            "--search-strategy",
            "AVERAGE_CPA_PER_CAMPAIGN",
            "--smart-search-average-cpa",
            "4",
            "--smart-search-goal-id",
            "111",
        ],
    ),
    (
        "campaigns",
        "update",
        [
            "campaigns",
            "update",
            "--id",
            "55",
            "--type",
            "SMART_CAMPAIGN",
            "--search-strategy",
            "PAY_FOR_CONVERSION_CRR",
            "--smart-search-crr",
            "15",
            "--smart-search-goal-id",
            "777",
        ],
    ),
    # --- issue #368: SmartCampaign.BiddingStrategy.Network typed flags ---
    (
        "campaigns",
        "add",
        [
            "campaigns",
            "add",
            "--name",
            "Test Smart Network NetworkDefault",
            "--start-date",
            "2026-06-01",
            "--type",
            "SMART_CAMPAIGN",
            "--counter-id",
            "123",
            "--network-strategy",
            "NETWORK_DEFAULT",
            "--smart-network-limit-percent",
            "80",
        ],
    ),
    (
        "campaigns",
        "update",
        [
            "campaigns",
            "update",
            "--id",
            "55",
            "--type",
            "SMART_CAMPAIGN",
            "--network-strategy",
            "AVERAGE_ROI",
            "--smart-network-reserve-return",
            "30",
            "--smart-network-roi-coef",
            "1.5",
            "--smart-network-goal-id",
            "555",
        ],
    ),
    (
        "campaigns",
        "add",
        [
            "campaigns",
            "add",
            "--name",
            "Test Notify+Time",
            "--start-date",
            "2026-06-01",
            "--type",
            "TEXT_CAMPAIGN",
            "--search-strategy",
            "HIGHEST_POSITION",
            "--network-strategy",
            "SERVING_OFF",
            "--sms-events",
            "FINISHED",
            "--sms-time-from",
            "09:00",
            "--sms-time-to",
            "18:00",
            "--notification-email",
            "ops@example.com",
            "--notification-send-warnings",
            "YES",
            "--time-targeting-schedule",
            "1A0123456789ABCDEFGHIJKL",
            "--consider-working-weekends",
            "YES",
        ],
    ),
    (
        "campaigns",
        "update",
        [
            "campaigns",
            "update",
            "--id",
            "12345",
            "--name",
            "Renamed Campaign",
            "--budget",
            "25000000",
            "--end-date",
            "2026-12-31",
        ],
    ),
    (
        "adgroups",
        "add",
        [
            "adgroups",
            "add",
            "--campaign-id",
            "12",
            "--name",
            "Group",
            "--region-ids",
            "225",
        ],
    ),
    (
        "adgroups",
        "add",
        [
            "adgroups",
            "add",
            "--campaign-id",
            "12",
            "--name",
            "Dyn Group",
            "--type",
            "DYNAMIC_TEXT_AD_GROUP",
            "--domain-url",
            "example.com",
            "--region-ids",
            "225",
        ],
    ),
    (
        "adgroups",
        "update",
        [
            "adgroups",
            "update",
            "--id",
            "14",
            "--name",
            "Renamed group",
            "--region-ids",
            "225",
        ],
    ),
    (
        "ads",
        "add",
        [
            "ads",
            "add",
            "--adgroup-id",
            "100",
            "--type",
            "TEXT_AD",
            "--title",
            "Buy now",
            "--text",
            "Best deals on widgets, fast shipping",
            "--href",
            "https://example.com",
            "--title2",
            "Free delivery",
            "--display-url-path",
            "deals",
            "--mobile",
            "NO",
            "--vcard-id",
            "111",
            "--sitelink-set-id",
            "222",
            "--turbo-page-id",
            "333",
            "--ad-extensions",
            "444,555",
        ],
    ),
    (
        "ads",
        "add",
        [
            "ads",
            "add",
            "--adgroup-id",
            "100",
            "--type",
            "TEXT_IMAGE_AD",
            "--image-hash",
            "ygqa6jmlkgsbz7vnewp0",
            "--href",
            "https://example.com",
            "--turbo-page-id",
            "777",
        ],
    ),
    (
        "ads",
        "add",
        [
            "ads",
            "add",
            "--adgroup-id",
            "100",
            "--type",
            "MOBILE_APP_AD",
            "--title",
            "Install our app",
            "--text",
            "Best mobile shopping experience",
            "--action",
            "INSTALL",
        ],
    ),
    (
        "ads",
        "update",
        [
            "ads",
            "update",
            "--id",
            "7",
            "--type",
            "TEXT_AD",
            "--title",
            "Updated title",
            "--text",
            "Updated text content",
            "--href",
            "https://example.com/new",
            "--title2",
            "Updated second headline",
            "--display-url-path",
            "updated",
            "--vcard-id",
            "111",
            "--sitelink-set-id",
            "222",
            "--turbo-page-id",
            "333",
        ],
    ),
    (
        "ads",
        "update",
        [
            "ads",
            "update",
            "--id",
            "7",
            "--type",
            "TEXT_AD",
            "--callouts-add",
            "111,222",
            "--callouts-remove",
            "333",
        ],
    ),
    (
        "ads",
        "update",
        [
            "ads",
            "update",
            "--id",
            "7",
            "--type",
            "TEXT_IMAGE_AD",
            "--turbo-page-id",
            "555",
        ],
    ),
    (
        "keywords",
        "add",
        [
            "keywords",
            "add",
            "--adgroup-id",
            "100",
            "--keyword",
            "laptop",
            "--bid",
            "1500000",
            "--context-bid",
            "900000",
            "--user-param-1",
            "src=test",
            "--user-param-2",
            "uid=42",
        ],
    ),
    (
        "keywords",
        "update",
        [
            "keywords",
            "update",
            "--id",
            "321",
            "--keyword",
            "renamed laptop",
            "--user-param-1",
            "src=upd",
            "--user-param-2",
            "uid=99",
        ],
    ),
    # --- issue #118: lifecycle fixtures (SelectionCriteria.Ids family) ---
    (
        "campaigns",
        "suspend",
        ["campaigns", "suspend", "--id", "12"],
    ),
    (
        "campaigns",
        "unarchive",
        ["campaigns", "unarchive", "--id", "12"],
    ),
    (
        "ads",
        "suspend",
        ["ads", "suspend", "--id", "7"],
    ),
    (
        "ads",
        "resume",
        ["ads", "resume", "--id", "7"],
    ),
    (
        "ads",
        "archive",
        ["ads", "archive", "--id", "7"],
    ),
    (
        "ads",
        "unarchive",
        ["ads", "unarchive", "--id", "7"],
    ),
    (
        "keywords",
        "resume",
        ["keywords", "resume", "--id", "8"],
    ),
    (
        "audiencetargets",
        "suspend",
        ["audiencetargets", "suspend", "--id", "16"],
    ),
    (
        "audiencetargets",
        "resume",
        ["audiencetargets", "resume", "--id", "16"],
    ),
    (
        "dynamictextadtargets",
        "suspend",
        ["dynamicads", "suspend", "--id", "17"],
    ),
    (
        "dynamictextadtargets",
        "resume",
        ["dynamicads", "resume", "--id", "17"],
    ),
    (
        "smartadtargets",
        "suspend",
        ["smartadtargets", "suspend", "--id", "22"],
    ),
    (
        "smartadtargets",
        "resume",
        ["smartadtargets", "resume", "--id", "22"],
    ),
    # --- issue #183 bucket B: media-payload fixtures ---
    (
        "adimages",
        "add",
        [
            "adimages",
            "add",
            "--name",
            "test-image.png",
            "--image-data",
            "aVZCT1J3MEtHZ29BQUFBTlNVaEV1Z0FBQUFFQUFBQUJDQVlBQUFBPQ==",
        ],
    ),
    (
        "advideos",
        "add",
        [
            "advideos",
            "add",
            "--url",
            "https://example.com/video.mp4",
            "--name",
            "Promo video",
        ],
    ),
    (
        "vcards",
        "add",
        [
            "vcards",
            "add",
            "--campaign-id",
            "100",
            "--country",
            "Russia",
            "--city",
            "Moscow",
            "--company-name",
            "Test Company",
            "--work-time",
            "1#5#9#0#18#0",
            "--phone-country-code",
            "+7",
            "--phone-city-code",
            "495",
            "--phone-number",
            "1234567",
        ],
    ),
    # --- issue #183 bucket A: adextensions / retargeting add fixtures ---
    (
        "adextensions",
        "add",
        [
            "adextensions",
            "add",
            "--callout-text",
            "Free shipping",
        ],
    ),
    (
        "retargetinglists",
        "add",
        [
            "retargeting",
            "add",
            "--name",
            "Cart abandoners",
            "--type",
            "RETARGETING",
            "--rule",
            "ANY:1234567890:30",
        ],
    ),
]

PAYLOAD_COVERED_COMMANDS = {f"{argv[0]}.{argv[1]}" for _, _, argv in PAYLOAD_CASES}
