#!/usr/bin/env bash
# Manual checklist for commands that must not be run by automated smoke tests.

set -euo pipefail

cat <<'EOF'
direct-cli DANGEROUS commands manual checklist

This script is documentation, not an executable smoke runner.
Do not run these commands automatically against production or sandbox accounts.

Agency/account mutations:
  - direct agencyclients add ...
  - direct agencyclients update ...
  - direct agencyclients delete ...
  - direct agencyclients add-passport-organization ...
  - direct agencyclients add-passport-organization-member ...

Local credential mutations:
  - direct auth login ...
  - direct auth use ...

V4 Live finance money mutations (0.3.3 exposes dry-run-only previews):
  - direct v4finance transfer-money --from-campaign-id ... --to-campaign-id ... --amount ... --currency RUB --dry-run
  - direct v4finance pay-campaigns --campaign-ids ... --amount ... --contract-id ... --pay-method Bank --currency RUB --dry-run

Browser-driven Мастер кампаний mutations (no API surface, no --sandbox
equivalent -- these always hit a real Yandex account; verify on one
non-critical campaign, confirming before/after state in the web UI):
  - direct masters suspend <campaign_id>
  - direct masters resume <campaign_id>

Interactive human-in-the-loop login (opens a visible browser window and
blocks waiting for a person to sign in -- cannot run unattended):
  - direct masters login

Production commands that are only allowed in automated smoke tests with --sandbox:
  - direct bids set ...
  - direct bids set-auto ...
  - direct keywordbids set ...
  - direct keywordbids set-auto ...
  - direct bidmodifiers set ...
  - direct ads moderate ...
  - direct clients update ...
  - direct campaigns delete ...
  - direct adgroups delete ...
  - direct ads delete ...
  - direct keywords delete ...
  - direct audiencetargets delete ...
  - direct dynamicads delete ...
  - direct dynamicfeedadtargets delete ...
  - direct feeds delete ...
  - direct negativekeywordsharedsets delete ...
  - direct retargeting delete ...
  - direct smartadtargets delete ...
  - direct campaigns suspend/resume/archive/unarchive ...
  - direct ads suspend/resume/archive/unarchive ...
  - direct keywords suspend/resume ...

Use scripts/test_safe_commands.sh for production read-only smoke tests.
Use scripts/test_sandbox_write.sh for sandbox/VCR write smoke tests.
EOF

exit 1
